const CREATE_ITEM = "CREATE_ITEM";
const ADD_CARD = "ADD_CARD";
const UPDATE_CARD_STATUS = "UPDATE_CARD_STATUS";
const REMOVE_CARD = "REMOVE_CARD";
const REMOVE_ITEM = "REMOVE_ITEM";
const API_INTERACTION_ERR = "API_INTERACTION_ERR";

export default {
  CREATE_ITEM,
  ADD_CARD,
  UPDATE_CARD_STATUS,
  REMOVE_CARD,
  REMOVE_ITEM,
  API_INTERACTION_ERR,
};
